### ISSUE TITLE
Request: update index.csv when downloading data, after each dataset

### ISSUE THREAD

**Issue by AuSpotter** [pofatu/pygeoroc#5]
If a download is interrupted, it seems that index.csv is not created. Therefore, when conducting large downloads, all the files need to be re-downloaded - this has happened to be a few times as it seems there is a server timeout issue when pulling many of the rock datasets.

**Comment by xrotwang** [comment]
@AuSpotter sorry for getting to this so late - vacations got in between. Could this issue be the cause for #4 as well? I.e. the botched download resulting in empty CSV files, thus invalid table creation statements because there are no columns?

**Comment by xrotwang** [comment]
I guess, a `try ... except` around this line
https://github.com/pofatu/pygeoroc/blob/aadf0de99187001c0fd9833318ebace465615b67/src/pygeoroc/commands/download.py#L48
could fix this problem. We'd still need to tell the user that something went wrong - so the download was imcomplete. But at least we could record what was already downloaded.

**Comment by xrotwang** [comment]
Downloading has been completely refactored due to the new source location of the georoc data.
